'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {fixture}=require('./extension-fixture.cjs');
(async()=>{
  let cleanup;const f=await fixture({after:fn=>{cleanup=fn;}});
  f.config.items.push({id:'sword',label:'Espada de ferro',descriptor:'500:Skyrim.esm',category:'WEAP'});
  f.config.items.push({id:'lockpick',label:'Lockpick',descriptor:'a:Skyrim.esm'});
  for(let i=1;i<=24;i++)f.config.weathers.push({id:'storm_'+i,label:'Tempestade '+i,descriptor:'81a:Skyrim.esm'});
  f.actors.get(200).inventory={entries:[{baseId:0x500,count:9},{baseId:10,count:100}]};
  await f.db.query('INSERT INTO character_inventory(character_id,base_id,count) VALUES (1,10,100),(2,10,3)');
  await f.db.query('INSERT INTO character_inventory(character_id,base_id,count) VALUES (2,1280,3)');
  await f.db.query("INSERT INTO containers(id,object_id,label,owner_character_id) VALUES (1,'abc:Skyrim.esm','Baú da oficina',2)");
  await f.db.query('INSERT INTO container_inventory(container_id,base_id,count) VALUES (1,1280,4)');
  const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const output=path.resolve(__dirname,'../artifacts/ui-ux');fs.mkdirSync(output,{recursive:true});
  const tab=name=>page.getByRole('tab',{name,exact:true});
  const action=name=>page.getByRole('button',{name,exact:true});
  const assertPopup=async()=>{
    const trigger=await page.locator('[role="combobox"][aria-expanded="true"]').boundingBox(),menu=await page.getByRole('listbox').boundingBox(),panel=await page.locator('#aetherius-admin').boundingBox();
    assert(menu.x>=panel.x && menu.y>=panel.y && menu.x+menu.width<=panel.x+panel.width+1 && menu.y+menu.height<=panel.y+panel.height+1,'dropdown must stay inside the panel');
    assert(Math.abs(menu.x-trigger.x)<=1,'dropdown must align with its own trigger');
    assert(Math.min(Math.abs(menu.y-trigger.y-trigger.height-4),Math.abs(trigger.y-menu.y-menu.height-4))<=2,'dropdown must open directly above or below its trigger');
  };
  const choose=async(label,option)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await assertPopup();await page.getByRole('option',{name:option,exact:true}).click();};
  try {
    await page.exposeFunction('adminBackend',message=>f.service.handle(100,message));
    await page.setContent('<!doctype html><html><head></head><body style="background:#333"></body></html>');
    await page.addStyleTag({path:path.resolve(__dirname,'../ui/admin.css')});
    await page.evaluate(()=>{window.adminFocusHistory=[];window.skyrimPlatform={sendMessage:(kind,type,data)=>{if(kind==='aetherius-admin:focus')window.adminFocusHistory.push(type);if(kind==='cef::ui:event')window.adminBackend(data).then(response=>window.AetheriusAdmin.receive(response));}};});
    await page.addScriptTag({path:path.resolve(__dirname,'../ui/app.js')});
    await page.evaluate(()=>window.AetheriusAdmin.toggle());
    await action('Ir até jogador').waitFor();
    assert.equal(await tab('RP / Ferramentas').count(),0);
    assert.equal(await action('Selecionar ação').count(),0);
    assert(await action('Ir até jogador').isDisabled());
    assert.equal(await action('Ir até jogador').evaluate(el=>getComputedStyle(el).opacity),'0.38');
    assert((await page.locator('.aap-summary').innerText()).includes('Ir até jogador - Move você para a localização do jogador.'));
    const panelBox=await page.locator('#aetherius-admin').boundingBox();assert(panelBox.width<=1042);assert(panelBox.height<=782);
    assert.equal(await page.locator('#aetherius-admin').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(21, 27, 35, 0.88)');
    await tab('Administração').click();await action('Modo de atendimento').click();await page.locator('.aap-mode-off').first().waitFor();
    assert(await action('Câmera livre · Desativado').isEnabled());assert(await action('Invulnerabilidade · Desativado').isEnabled());await action('Fechar').click();await tab('Moderação').click();f.advance(11000);
    await page.screenshot({path:path.join(output,'moderation-no-player.png')});
    await page.locator('.aap-player').nth(1).click();
    assert(await action('Ir até jogador').isEnabled());
    assert.equal(await action('Ir até jogador').evaluate(el=>getComputedStyle(el).opacity),'1');
    assert.equal(await action('Ir até jogador').locator('p,button').count(),0);
    await action('Ir até jogador').click();await page.getByRole('dialog').waitFor();
    assert(await page.getByLabel('Motivo da ação').isVisible());await action('Cancelar').click();
    const summary=await page.locator('.aap-summary').boundingBox(),refresh=await action('Atualizar jogadores').boundingBox();
    assert(Math.abs(summary.y+summary.height-refresh.y-refresh.height)<30,'summary should align with sidebar bottom');
    const title=await page.getByRole('heading',{name:'Moderação',exact:true}).boundingBox();
    assert(Math.abs(summary.x-title.x)<2,'summary should align with the left of the tab');
    const directButton=await action('Ir até jogador').boundingBox();assert.equal(directButton.width,192);assert.equal(directButton.height,44);
    await tab('Staff').click();assert(await page.locator('.aap-action-denied').count()>0);
    assert.equal(await page.locator('.aap-action-denied').first().evaluate(el=>getComputedStyle(el).opacity),'1');
    await tab('Administração').click();
    for(const name of ['Executar animação','Investigar mundo','Modo de atendimento','Clima do servidor','Spawnar NPC'])assert(await action(name).isVisible());
    assert.equal(await action('Revelar identidade').count(),0);
    for(const [width,height] of [[1280,720],[1920,1080],[2560,1440]]){
      await page.setViewportSize({width,height});
      for(const selector of ['#aetherius-admin','.aap-content','.aap-nav'])assert(await page.locator(selector).evaluate(el=>el.scrollWidth<=el.clientWidth),selector+' overflow at '+width);
      await page.screenshot({path:path.join(output,`administration-${width}.png`)});
    }
    await page.setViewportSize({width:1920,height:1080});
    await action('Modo de atendimento').click();await page.locator('.aap-mode-off').first().waitFor();
    assert.equal(await page.locator('.aap-mode-off').count(),6);assert.equal(await page.getByLabel('Motivo da ação').count(),0);
    await action('Invulnerabilidade · Desativado').click();await action('Invulnerabilidade · Ativo').waitFor();
    assert.equal(await action('Invulnerabilidade · Ativo').getAttribute('aria-pressed'),'true');
    assert.equal(await action('Invulnerabilidade · Ativo').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(44, 96, 70)');
    await page.screenshot({path:path.join(output,'staff-modes.png')});
    await action('Desativar todos').click();await action('Invulnerabilidade · Desativado').waitFor();
    assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM aetherius_admin_operations WHERE action='staff.mode' AND status='succeeded'"))[0].n,2);
    await action('Câmera livre · Desativado').click();await page.locator('#aetherius-admin').waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>window.adminFocusHistory.at(-1)),false);
    assert(f.sent.some(s=>s.data?.values?.freecam && s.user===0 && !s.data.cameraLocation));
    f.advance(1000);await page.evaluate(()=>window.AetheriusAdmin.toggle());await tab('Administração').click();await action('Modo de atendimento').click();await action('Câmera livre · Ativo').waitFor();
    await action('Câmera livre · Ativo').click();await action('Câmera livre · Desativado').waitFor();
    await action('Fechar').click();await page.locator('.aap-player').nth(1).click();f.advance(11000);
    await action('Clima do servidor').click();await page.getByText('Clima natural do jogo',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('Raio').count(),0);
    await page.getByRole('dialog').getByText('25 resultados · página 1',{exact:true}).waitFor();
    for(const [width,height] of [[1280,720],[1920,1080],[2560,1440]]){
      await page.setViewportSize({width,height});const combo=page.getByRole('dialog').getByRole('combobox');await combo.click();await assertPopup();
      assert(await page.getByRole('listbox').evaluate(el=>el.scrollHeight>el.clientHeight));
      await combo.press('End');assert(await page.getByRole('listbox').evaluate(el=>el.scrollTop>0));await assertPopup();
      await page.screenshot({path:path.join(output,`weather-dropdown-long-${width}.png`)});await combo.press('Escape');
    }
    await page.setViewportSize({width:1920,height:1080});
    await page.getByLabel('Buscar em Climas',{exact:true}).fill('limpo');await page.getByLabel('Buscar em Climas',{exact:true}).press('Enter');
    await page.getByRole('dialog').getByText('1 resultados · página 1',{exact:true}).waitFor();
    for(const [width,height] of [[1280,720],[1920,1080],[2560,1440]]){
      await page.setViewportSize({width,height});await page.getByRole('dialog').getByRole('combobox').click();await assertPopup();
      await page.screenshot({path:path.join(output,`weather-dropdown-${width}.png`)});await page.getByRole('dialog').getByRole('combobox').press('Escape');
    }
    await page.setViewportSize({width:1920,height:1080});await page.getByRole('dialog').getByRole('combobox').click();await assertPopup();await page.getByRole('option',{name:'Céu limpo',exact:true}).click();
    await page.getByLabel('Motivo da ação').fill('Teste do clima geral');await action('Aplicar ao servidor').click();
    await page.getByText('Clima configurado: Céu limpo',{exact:true}).waitFor();
    await page.screenshot({path:path.join(output,'weather-server.png')});
    await action('Restaurar clima natural').click();await page.getByText('Clima natural do jogo',{exact:true}).waitFor();
    await action('Fechar').click();f.advance(11000);
    await tab('Catálogos').click();
    assert.equal(await page.getByRole('combobox',{name:'Catálogo',exact:true}).count(),0);
    assert.equal(await page.locator('select:visible').count(),0);
    const searchBox=await page.getByLabel('Buscar nos inventários').boundingBox(),selectorBox=await page.getByRole('combobox',{name:'Buscar por',exact:true}).boundingBox();
    assert.equal(searchBox.width,320);assert.equal(searchBox.height,40);assert.equal(selectorBox.height,40);assert.equal(searchBox.y,selectorBox.y);
    await page.getByLabel('Buscar nos inventários').fill('lockpick');await page.getByLabel('Buscar nos inventários').press('Enter');
    await page.getByText('Total entre jogadores: 200 · 2 personagem(ns)',{exact:true}).waitFor();
    assert.equal(await page.getByText('Visível · Quantidade: 100',{exact:true}).count(),2);
    for(const [width,height] of [[1280,720],[1920,1080],[2560,1440]]){
      await page.setViewportSize({width,height});
      assert(await page.locator('.aap-content').evaluate(el=>el.scrollWidth<=el.clientWidth));
      await page.screenshot({path:path.join(output,'item-totals-'+width+'.png')});
    }
    await page.setViewportSize({width:1920,height:1080});
    await action('Ver inventário de Visível (personagem 2)').click();
    await page.getByRole('heading',{name:'Inventário de Visível',exact:true}).waitFor();
    assert(await page.getByRole('heading',{name:'Espada de ferro',exact:true}).isVisible());
    assert(await page.getByText('Quantidade: 100',{exact:true}).isVisible());
    const backBox=await action('Voltar à pesquisa').boundingBox();assert(backBox.width<200);assert.equal(backBox.height,36);
    await page.screenshot({path:path.join(output,'inventory-back-compact.png')});
    await action('Voltar à pesquisa').click();await page.getByText('Total entre jogadores: 200 · 2 personagem(ns)',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('Buscar nos inventários').inputValue(),'lockpick');
    await choose('Buscar por','Jogador');await action('Ver inventário').first().waitFor();
    await page.getByLabel('Buscar nos inventários').fill('Visível');await page.getByLabel('Buscar nos inventários').press('Enter');await action('Ver inventário').nth(1).waitFor();
    await action('Ver inventário').nth(1).click();await page.getByRole('heading',{name:'Inventário de Visível',exact:true}).waitFor();
    await action('Voltar à pesquisa').click();await action('Ver inventário').first().waitFor();
    assert.equal(await page.getByRole('combobox',{name:'Buscar por',exact:true}).innerText(),'Jogador');
    assert.equal(await page.getByLabel('Buscar nos inventários').inputValue(),'Visível');
    f.advance(11000);
    await tab('Administração').click();await action('Investigar mundo').click();
    assert.equal(await page.getByLabel('Motivo da ação').count(),0);await action('Confirmar ação').click();
    await page.getByRole('status').filter({hasText:'Diagnóstico recebido'}).waitFor();
    await action('Entregar item').click();await page.getByLabel('Buscar em Itens',{exact:true}).fill('lockpick');await page.getByLabel('Buscar em Itens',{exact:true}).press('Enter');
    await page.getByRole('dialog').getByText('1 resultados · página 1',{exact:true}).waitFor();
    await page.getByRole('dialog').getByRole('combobox').click();await page.getByRole('option',{name:'Lockpick',exact:true}).click();await action('Cancelar').click();
    f.advance(11000);
    assert.equal(await action('Configurar zona de NPCs').count(),0);
    f.actors.get(200).locationalData.pos=[90000,45000,100];
    await action('Spawnar NPC').click();
    assert.equal(await page.getByLabel('Motivo da ação').count(),0);assert.equal(await page.getByLabel('Identificador (sem espaços)').count(),0);
    await page.getByRole('dialog').getByRole('button',{name:'Spawnar NPC',exact:true}).click();
    assert.equal(await page.getByRole('combobox',{name:'NPC',exact:true}).getAttribute('aria-invalid'),'true');
    const npc=page.getByRole('combobox',{name:'NPC',exact:true});await npc.press('Escape');await npc.click();await assertPopup();await page.getByRole('option',{name:/Cão/}).click();
    await page.screenshot({path:path.join(output,'instant-npc.png')});
    await page.getByRole('dialog').getByRole('button',{name:'Spawnar NPC',exact:true}).click();await page.getByRole('status').filter({hasText:'NPC criado na sua posição'}).waitFor();
    assert.equal((await f.db.query("SELECT COUNT(*) AS n FROM aetherius_admin_world WHERE kind='zone'"))[0].n,0);
    const spawned=[...f.actors.keys()].filter(id=>id>=0xff000000);assert.equal(spawned.length,1);assert.deepEqual(f.actors.get(spawned[0]).locationalData,f.actors.get(100).locationalData);
    await tab('Auditoria').click();await choose('Resultado','Concluída');await action('Filtrar').click();await page.locator('tbody tr').first().waitFor();
    assert.deepEqual(errors,[]);console.log('PASS SQLite-backed UI: compact layout, self-only modes, camera releases focus, inventories, immediate NPC spawn, dropdown alignment/bounds/scrolling, audit, three viewport sizes.');
  } finally {await browser.close();await cleanup();}
})().catch(e=>{console.error(e);process.exitCode=1;});
