'use strict';
const { test } = require('node:test'); const assert = require('node:assert/strict');
const { createService } = require('../gamemode/service.cjs');
const { validate } = require('../gamemode/protocol.cjs');
const { actions } = require('../gamemode/catalog.cjs');
function fixture() {
  const operator = { actorId: 100, accountId: 1, characterId: 10, session: 'session_operator_000', role: 'admin', label: 'Staff' };
  const target = { actorId: 200, accountId: 2, characterId: 20, session: 'session_target_00000', label: 'Desconhecido' };
  const calls = []; const operations = new Map();
  const auth = { role: 'admin', permissions: ['panel.open', 'players.view', 'logs.view', ...actions.map(a => a.permission)] };
  const host = { session: id => id === 100 ? operator : id === 200 ? target : null, players: () => [operator, target], visibleName: (_, person) => person.label, realName: () => 'Nome Protegido', teleport: (...args) => calls.push(['teleport', ...args]), kick: person => calls.push(['kick', person]), resolveItem: () => 123 };
  const store = { authorize: async () => auth, targetRole: async () => null, denied: async () => calls.push(['denied']),
    reserve: async op => { if (operations.has(op.requestId)) return { ...operations.get(op.requestId), fresh: false }; operations.set(op.requestId, { hash: op.hash }); return { fresh: true }; },
    finish: async (op, result) => { operations.get(op.requestId).result = result; },
    mutate: async op => { calls.push(['mutate', op]); const result = { status: 'succeeded', message: 'ok' }; operations.get(op.requestId).result = result; return result; },
    audit: async (_, sensitive) => ({ rows: [], sensitive })
  };
  const service = createService({ host, store, enabledActions: actions.filter(a => !a.unavailable).map(a => a.id), items: [{ id: 'bread', label: 'Pão' }] });
  const message = (type = 'action', data) => ({ version: 1, requestId: 'request_0001', type, data: data || { action: 'player.teleportTo', target: { actorId: 200, session: target.session }, reason: 'Atendimento de suporte', params: {} } });
  return { operator, target, calls, operations, auth, host, store, service, message };
}
test('unauthorized player receives no players, capabilities or effects', async () => { const f = fixture(); f.store.authorize = async () => null; const response = await f.service.handle(100, f.message('open', {})); assert.equal(response.code, 'FORBIDDEN'); assert.equal(response.data, undefined); assert.deepEqual(f.calls, [['denied']]); });
test('permission to open alone does not grant access to players', async () => { const f = fixture(); f.auth.permissions = ['panel.open']; const response = await f.service.handle(100, f.message('open', {})); assert.equal(response.code, 'FORBIDDEN'); });
test('player projection omits account, character and protected identity', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('open', {})); assert.equal(response.status, 'succeeded'); assert.deepEqual(Object.keys(response.data.players.rows[1]).sort(), ['actorId', 'label', 'self', 'session']); assert(!JSON.stringify(response).includes('Nome Protegido')); });
test('search cannot disclose hidden names', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('players', { query: 'Nome Protegido' })); assert.equal(response.data.total, 0); });
test('actor spoofing and unknown payload fields are rejected', async () => { const f = fixture(); for (const message of [{ ...f.message(), accountId: 1 }, { ...f.message(), role: 'owner' }, f.message('action', { ...f.message().data, script: 'anything' })]) assert.equal((await f.service.handle(100, message)).code, 'INVALID'); assert.equal(f.calls.length, 0); });
test('fractional, negative, excessive and NaN economy quantities are rejected', () => { const f = fixture(); for (const amount of [-1, 1.5, NaN, 1000001, '100']) assert.throws(() => validate(f.message('action', { ...f.message().data, action: 'economy.setGold', params: { amount } }))); });
test('motivation is enforced on server', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('action', { ...f.message().data, reason: '  ' })); assert.equal(response.code, 'INVALID'); assert.equal(f.calls.length, 0); });
test('stale target session cannot be acted upon', async () => { const f = fixture(); const message = f.message(); f.target.session = 'replacement_session_00'; const response = await f.service.handle(100, message); assert.equal(response.code, 'SESSION_EXPIRED'); assert.equal(f.calls.length, 0); });
test('revocation between reservation and execution prevents effects', async () => { const f = fixture(); const reserve = f.store.reserve; f.store.reserve = async op => { const result = await reserve(op); f.auth.permissions = []; return result; }; const result = await f.service.handle(100, f.message()); assert.equal(result.status, 'rejected'); assert.equal(f.calls.length, 0); });
test('disconnect during audit reservation prevents effects', async () => { const f = fixture(); const reserve = f.store.reserve; f.store.reserve = async op => { const result = await reserve(op); f.host.session = () => null; return result; }; const result = await f.service.handle(100, f.message()); assert.equal(result.status, 'rejected'); assert.equal(f.calls.length, 0); });
test('failed audit reservation prevents execution', async () => { const f = fixture(); f.store.reserve = async () => { throw new Error('db unavailable'); }; assert.equal((await f.service.handle(100, f.message())).status, 'rejected'); assert.equal(f.calls.length, 0); });
test('duplicate click executes once and returns stored result', async () => { const f = fixture(); const first = await f.service.handle(100, f.message()); const second = await f.service.handle(100, f.message()); assert.equal(f.calls.length, 1); assert.equal(second.status, first.status); });
test('simultaneous identical requests execute once', async () => { const f = fixture(); await Promise.all([f.service.handle(100, f.message()), f.service.handle(100, f.message())]); assert.equal(f.calls.length, 1); });
test('same request identifier with altered body is rejected', async () => { const f = fixture(); await f.service.handle(100, f.message()); const response = await f.service.handle(100, f.message('action', { ...f.message().data, reason: 'Outro motivo de suporte' })); assert.equal(response.code, 'CONFLICT'); assert.equal(f.calls.length, 1); });
test('pending operation from a previous runtime is never replayed', async () => { const f = fixture(); const reserve = f.store.reserve; f.store.reserve = async op => { await reserve(op); return { fresh: false, hash: op.hash }; }; const response = await f.service.handle(100, f.message()); assert.equal(response.status, 'unknown'); assert.equal(f.calls.length, 0); });
test('higher or equal role cannot be targeted by administrator', async () => { const f = fixture(); f.store.targetRole = async () => 'owner'; assert.equal((await f.service.handle(100, f.message())).code, 'FORBIDDEN'); assert.deepEqual(f.calls, [['denied']]); });
test('target promoted while reservation is pending cannot be acted upon', async () => { const f = fixture(); const reserve = f.store.reserve; f.store.reserve = async op => { const result = await reserve(op); f.store.targetRole = async () => 'owner'; return result; }; assert.equal((await f.service.handle(100, f.message())).code, 'FORBIDDEN'); assert.equal(f.calls.length, 0); });
test('self kick is rejected', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'player.kick', target: { actorId: 100, session: f.operator.session } })); assert.equal(response.code, 'INVALID'); });
test('forbidden identity is not returned', async () => { const f = fixture(); f.auth.permissions = ['panel.open', 'players.view']; const response = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'identity.reveal' })); assert.equal(response.code, 'FORBIDDEN'); assert(!JSON.stringify(response).includes('Nome Protegido')); });
test('identity is returned only after audit completion', async () => { const f = fixture(); f.store.finish = async () => { throw new Error('db down'); }; const response = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'identity.reveal' })); assert.equal(response.status, 'rejected'); assert(!JSON.stringify(response).includes('Nome Protegido')); });
test('unconfigured item is refused before transaction', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'inventory.grant', params: { item: 'forbidden', quantity: 1 } })); assert.equal(response.status, 'rejected'); assert.equal(f.calls.length, 0); });
test('failed item resolver does not grant anything', async () => { const f = fixture(); f.host.resolveItem = () => { throw new Error('missing resolver'); }; const response = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'inventory.grant', params: { item: 'bread', quantity: 1 } })); assert.equal(response.status, 'rejected'); assert.equal(f.calls.length, 0); });
test('audit visibility is scoped separately from operational access', async () => { const f = fixture(); const response = await f.service.handle(100, f.message('audit', {})); assert.equal(response.data.sensitive, false); });
test('rate limiter bounds an authenticated emitter', async () => { const f = fixture(); let response; for (let i = 0; i < 21; i++) response = await f.service.handle(100, f.message('players', {})); assert.equal(response.code, 'RATE_LIMIT'); });
test('unimplemented actions never invoke a host function', async () => { const f = fixture(); const result = await f.service.handle(100, f.message('action', { ...f.message().data, action: 'player.ban' })); assert.equal(result.code, 'UNAVAILABLE'); assert.equal(f.calls.length, 0); });
module.exports = { fixture };
